print("==================================================")
print("  LuaDB Complete RDBMS Verification Suite (Verbose)  ")
print("==================================================")

dofile("tests/vfs_spec.lua")
dofile("tests/storage_spec.lua")
dofile("tests/sql_spec.lua")
dofile("tests/coroutine_spec.lua")
dofile("tests/embedding_spec.lua")
dofile("tests/cluster_spec.lua")
dofile("tests/live_cluster_spec.lua")
dofile("tests/json_spec.lua")
dofile("tests/foreign_key_spec.lua")
dofile("tests/advanced_features_spec.lua")
dofile("tests/bugfixes_spec.lua")
dofile("tests/examples_spec.lua")

print("\n==================================================")
print("   🎉 ALL VERIFICATION TESTS PASSED 100%!        ")
print("==================================================\n")
